[project]
name = "web-browsing-agent"
version = "0.1.0"
description = "Web Browsing Multi-Agent"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=0.141.0",
    "nest-asyncio>=1.6.0",
    "stagehand>=0.4.0",
    "streamlit",
]
